/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel;

import project.InsertUpdateDelete;
import java.sql.*;
import project.*;

/**
 *
 * @author abdullah
 */
public class Cancel_booking extends javax.swing.JFrame {

    /**
     * Creates new form Cancel_booking
     */
    public Cancel_booking() {
        initComponents();
    }
    String roomNo;
    String Query;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        confirm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        troom = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 51));
        jLabel2.setText("Room NO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 111, 108, -1));

        confirm.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        confirm.setText("CONFIRM");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        getContentPane().add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 195, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText("Cancel Booking");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 28, -1, -1));

        troom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(troom, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 111, 229, -1));

        jButton6.setText("X");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        roomNo = troom.getText();

        if (roomNo.equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter room number");
        } else {
            try {
                Connection con = Connectionprovider.getcon();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("select Status from rooms where roomNo='" + roomNo + "'");
                
                if (rs.next()) {
                    String currentStatus = rs.getString("Status");
                    if ("Not booked".equals(currentStatus)) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Room " + roomNo + " is already not booked!");
                    } else {
                        // Room is booked, ask for confirmation before cancelling
                        int confirmation = javax.swing.JOptionPane.showConfirmDialog(this, 
                            "Do you want to cancel booking for room " + roomNo + "?", 
                            "Confirm Cancellation", 
                            javax.swing.JOptionPane.YES_NO_OPTION);
                        
                        if (confirmation == javax.swing.JOptionPane.YES_OPTION) {
                            // User confirmed, proceed with cancellation
                            Query = "update rooms set Status ='Not booked' where roomNo='" + roomNo + "'";
                            InsertUpdateDelete.setData(Query, "");
                            javax.swing.JOptionPane.showMessageDialog(this, "Booking cancelled for room number: " + roomNo);
                        } else {
                            // User clicked No
                            javax.swing.JOptionPane.showMessageDialog(this, "Cancellation aborted for room " + roomNo);
                        }
                    }
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Room " + roomNo + " does not exist!");
                }
                
                con.close();
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_confirmActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cancel_booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cancel_booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cancel_booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cancel_booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cancel_booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirm;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField troom;
    // End of variables declaration//GEN-END:variables
}
